services:
  _defaults:
    autowire: true

  oxid_esales.command.module_activate_command:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Command\Module_Activate_Command
    tags:
      - { name: 'console.command', command: 'oe:module:activate' }
  oxid_esales.command.module_deactivate_command:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Command\Module_Deactivate_Command
    tags:
      - { name: 'console.command', command: 'oe:module:deactivate' }

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Command\Module_Install_Command:
    tags:
      - { name: 'console.command', command: 'oe:module:install' }

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Command\Module_Uninstall_Command:
    tags:
      - { name: 'console.command', command: 'oe:module:uninstall' }

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Command\Install_Module_Assets_Command:
    tags:
      - { name: 'console.command', command: 'oe:module:install-assets' }
