imports:
  - { resource: parameters.yaml }

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer_Config_Factory_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer_Config_Factory

  oxid_esales.html_sanitizer.config:
    class: Symfony\Component\Html_Sanitizer\Html_Sanitizer_Config
    factory: ['@Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer_Config_Factory_Interface', 'create']

  Symfony\Component\Html_Sanitizer\Html_Sanitizer_Interface:
    class: Symfony\Component\Html_Sanitizer\Html_Sanitizer
    arguments:
      - '@oxid_esales.html_sanitizer.config'

  Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer:
    arguments:
      - '@Symfony\Component\Html_Sanitizer\Html_Sanitizer_Interface'

  Oxid_Esales\Eshop_Community\Internal\Framework\Html\Allow_All_Html_Sanitizer:

  Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer_Factory:
    arguments:
      - '%oxid_esales.html_sanitizer_enabled%'
      - '@Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer'
      - '@Oxid_Esales\Eshop_Community\Internal\Framework\Html\Allow_All_Html_Sanitizer'

  Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer_Interface:
    factory: [ '@Oxid_Esales\Eshop_Community\Internal\Framework\Html\Html_Sanitizer_Factory', 'create' ]
    public: true