services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Bridge\Password_Service_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Bridge\Password_Service_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Service\Password_Verification_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Service\Password_Verification_Service

  Oxid_Esales\Eshop_Community\Internal\Utility\Authentication\Policy\Password_Policy_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Utility\Authentication\Policy\Password_Policy

  Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Generator\Random_Token_Generator_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Generator\Random_Token_Generator

  Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Bridge\Random_Token_Generator_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Authentication\Bridge\Random_Token_Generator_Bridge
    public: true
