services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context
    public: true
    arguments:
      $shopId: '%oxid_esales.current_shop_id%'
