imports:
  - { resource: Logger/services.yaml }

parameters:
  oxid_esales.multilingual_tables: []
  oxid_esales.skip_database_views_usage: false
  oxid_esales.show_update_views_button: true
  oxid_esales.multi_shop_tables: []

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Database\Query_Builder_Factory_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Database\Query_Builder_Factory
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Database\Connection_Factory_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Database\Connection_Factory
    arguments:
      $middlewares: !tagged doctrine.middleware
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Database\Connection_Parameter_Provider_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Database\Connection_Parameter_Provider
