services:
  _defaults:
    autowire: true
    public: false

  Oxid_Esales\Eshop_Community\Internal\Domain\Admin\Service\Admin_User_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Admin\Service\Admin_User_Service