services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\State\Module_State_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\State\Module_State_Service
    public: true