parameters:
  oxid_esales.templating.engine_template_extension: 'html.twig'

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop\Core\Config:
    factory: ['Oxid_Esales\Eshop\Core\Registry', 'getConfig']

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Template_Renderer_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Template_Renderer
    arguments:
      $filenameExtension: '%oxid_esales.templating.engine_template_extension%'
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Template_Renderer_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Template_Renderer_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Template_Engine_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Template_Engine

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Locator\Template_File_Locator:
    arguments:
      - '@Oxid_Esales\Eshop\Core\Config'

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Locator\Admin_Template_File_Locator:
    arguments:
      - '@Oxid_Esales\Eshop\Core\Config'

  oxid_esales.templating.admin.navigation.file.locator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Locator\Admin_Navigation_File_Locator
    arguments:
      - !tagged oxid.menu.file.locator
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Locator\Edition_Menu_File_Locator:
    tags:
      - { name: 'oxid.menu.file.locator', priority: 10 }
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Locator\Edition_User_File_Locator:
    tags:
      - { name: 'oxid.menu.file.locator', priority: 20 }
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'

  Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Cache\Shop_Template_Cache_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Templating\Cache\Shop_Template_Cache_Service
    arguments:
      - '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface'
      - '@oxid_esales.symfony.file_system'
      - '%oxid_esales.build_directory%'
