services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Dao\Product_Media_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Dao\Product_Media_Dao
    public: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Factory\Product_Media_Factory_Interface:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Factory\Product_Media_Factory

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_Service
    public: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_View_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_View_Service
    public: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Variant_Media_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Variant_Media_Service
    public: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_Upload_Processor_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_Upload_Processor
    arguments:
      $mediaConstraintValidator: '@Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Validator\Product_Media_Validator'
      $mediaUploader: '@oxid_esales.product.media.media_uploader'
    public: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_Path_Resolver_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Service\Product_Media_Path_Resolver

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Data_Mapper\Data_Mapper_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Data_Mapper\Data_Mapper

  oxid_esales.product.media.media_uploader:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Media_Uploader

  oxid_esales.product.media.constraint_validator.upload_validity:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Validator\Upload_Validity_Constraint_Validator
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.size:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Validator\File_Size_Constraint_Validator
    arguments:
      $minSizeKb: '%oxid_esales.product.media.file.min_size_kb%'
      $maxSizeKb: '%oxid_esales.product.media.file.max_size_kb%'
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.mime_type:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Validator\Mime_Type_Constraint_Validator
    arguments:
      $baseTypePrefix: 'image/'
      $mimeTypeGuesser: "@oxid_esales.symfony.mime_types"
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.file_extension:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Validator\File_Extension_Constraint_Validator
    arguments:
      $mimeTypeGuesser: "@oxid_esales.symfony.mime_types"
    tags:
      - { name: oxid.product_media.constraint_validator }

  Oxid_Esales\Eshop_Community\Internal\Domain\Product\Media\Validator\Product_Media_Validator:
    arguments:
      $validators: !tagged_iterator oxid.product_media.constraint_validator
