imports:
  - { resource: TemplateLogic/services.yaml }
  - { resource: Translator/services.yaml }

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Shop_Adapter_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Shop_Adapter

  Oxid_Esales\Eshop_Community\Internal\Framework\Config\Dao\Shop_Configuration_Setting_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Config\Dao\Shop_Configuration_Setting_Dao
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Theme\Config\Dao\Theme_Setting_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Theme\Config\Dao\Theme_Setting_Dao

  Oxid_Esales\Eshop_Community\Internal\Framework\Config\Utility\Shop_Setting_Encoder_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Config\Utility\Shop_Setting_Encoder

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Email\Email_Adapter_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Email\Symfony_Mailer_Adapter
    public: true
