services:
  _defaults:
    autowire: true
    public: false

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Template\Locator\Modules_Menu_File_Locator:
    tags:
      - { name: 'oxid.menu.file.locator', priority: -255 }
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'