services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Bridge_Interface:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Bridge
      arguments:
        $contactFormFactory: '@form.contact_form.contact_form_factory'
        $contactFormMessageBuilder: '@Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Message_Builder_Interface'
        $contactFormConfiguration: '@form.contact_form.contact_form_configuration'
      public: true

  form.contact_form.contact_form_factory:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Factory
      arguments:
        $contactFormConfiguration: '@form.contact_form.contact_form_configuration'
        $contactFormEmailValidator: '@form.contact_form.contact_form_email_validator'
        $requiredFieldsValidator: '@common.form.required_fields_validator'

  form.contact_form.contact_form_configuration:
      class: Oxid_Esales\Eshop_Community\Internal\Framework\Form_Configuration\Form_Configuration
      factory: ['@form.contact_form.contact_form_configuration_factory', 'getFormConfiguration']

  form.contact_form.contact_form_email_validator:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Email_Validator
      arguments:
        - '@Oxid_Esales\Eshop_Community\Internal\Utility\Email\Email_Validator_Service_Interface'

  Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Message_Builder_Interface:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Message_Builder
      arguments:
        - '@Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Shop_Adapter_Interface'

  form.contact_form.contact_form_configuration_factory:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Configuration_Factory
      arguments:
        - '@form.contact_form.contact_form_fields_configuration_data_provider'
        - '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface'

  form.contact_form.contact_form_fields_configuration_data_provider:
      class: Oxid_Esales\Eshop_Community\Internal\Domain\Contact\Form\Contact_Form_Fields_Configuration_Data_Provider
