services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Media\Dao\Media_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Dao\Media_Dao

  Oxid_Esales\Eshop_Community\Internal\Domain\Media\Data_Mapper\Data_Mapper_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Data_Mapper\Data_Mapper

  Oxid_Esales\Eshop_Community\Internal\Domain\Media\Media_Url_Generator_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Media\Media_Url_Generator
    public: true
    arguments:
      $alternativeImageUrl: '%oxid_esales.alternative_image_url%'
