services:
  _defaults:
    autowire: true
    public: false

  Symfony\Component\Http_Foundation\Request:
    factory: ['Symfony\Component\Http_Foundation\Request', 'createFromGlobals']
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Request\Request_Interface:
    alias: Symfony\Component\Http_Foundation\Request