parameters:
  oxid_esales.log_admin_queries: false

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Database\Logger\Query_Log_Filter_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Database\Logger\Query_Log_Filter
    arguments:
      $skipLogTags: '@=service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").getSkipLogTags()'

  Oxid_Esales\Eshop_Community\Internal\Framework\Database\Logger\Query_Log_Context_Extender_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Database\Logger\Query_Log_Context_Extender

  Psr\Log\Null_Logger:
    public: true

  Doctrine\DBAL\Logging\Middleware:
    arguments:
      $logger: '@=(parameter("oxid_esales.log_admin_queries") & service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").isAdmin()) ? service("database.psr_logger") : service("Psr\\Log\\NullLogger")'
    tags:
      - { name: doctrine.middleware }

  database.monolog_logger_factory:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Database\Logger\Query_Logger_Factory
    arguments:
      $loggerName: 'OXID Admin Logger'
      $streamHandler: '@database.monolog.stream_handler'

  database.psr_logger:
    class: Monolog\Logger
    factory: ['@database.monolog_logger_factory', 'create']

  database.monolog.stream_handler:
    class: Monolog\Handler\Stream_Handler
    arguments:
      $stream: '@=service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").getAdminLogFilePath()'
      $level: !php/const Psr\Log\Log_Level::DEBUG
    calls:
      - setFormatter: ['@Monolog\Formatter\Line_Formatter']

  Monolog\Formatter\Line_Formatter:
    calls:
      - includeStacktraces: []
