services:
    _defaults:
        autowire: true

    Oxid_Esales\Eshop_Community\Internal\Setup\Language\Language_Installer_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Setup\Language\Language_Installer
