services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\User_Rating_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\User_Rating_Service
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\User_Review_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\User_Review_Service
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\Review_And_Rating_Merging_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\Review_And_Rating_Merging_Service
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\User_Review_And_Rating_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\User_Review_And_Rating_Service
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\Rating_Calculator_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\Rating_Calculator_Service
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\Product_Rating_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Service\Product_Rating_Service
