services:
  _defaults:
    autowire: true

  oxid_esales.module.install.service.launched_shop_project_configuration_generator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Install\Service\Project_Configuration_Generator
    arguments:
      $context: '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface'
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Install\Service\Module_Installer_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Install\Service\Module_Installer
    arguments:
      - '@oxid_esales.module.install.service.bootstrap_module_installer'
    public: true