services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Content_Factory:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Seo_Url_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Add_Url_Parameters_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Include_Dynamic_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\If_Content_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Format_Price_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Script_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Format_Date_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Translate_Filter_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Translate_Function_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Format_Time_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\File_Size_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Style_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Truncate_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Translate_Salutation_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Format_Currency_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Wordwrap_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Include_Widget_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Smart_Wordwrap_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Input_Help_Logic:

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Template_Logic\Insert_New_Basket_Item_Logic_Twig:
