services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Dao\Product_Rating_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Dao\Product_Rating_Dao

  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Dao\Rating_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Dao\Rating_Dao

  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Dao\Review_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Dao\Review_Dao
