services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\DI_Container\Dao\Project_Yaml_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\DI_Container\Dao\Container_Aware_Project_Yaml_Dao
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'
      $context: '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Basic_Context_Interface'

  Oxid_Esales\Eshop_Community\Internal\Framework\DI_Container\Dao\Parameter_Dao_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\DI_Container\Dao\Parameter_Dao
    public: true
