services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\System_Requirements\System_Security_Checker_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\System_Requirements\System_Security_Checker
