services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Facade\Active_Modules_Data_Provider_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Facade\Active_Modules_Data_Provider

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Module_Configuration_Dao_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Module_Configuration_Dao_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Shop_Configuration_Dao_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Shop_Configuration_Dao_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Module_Setting_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Module_Setting_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Dao\Shop_Environment_Misconfiguration_Event_Subscriber:
    tags:
      - { name: kernel.event_subscriber }

  oxid_esales.module.configuration.class_extensions_export_data_mapper:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Data_Mapper\Module_Configuration\Class_Extensions_Export_Data_Mapper

  oxid_esales.module.configuration.controllers_export_data_mapper:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Data_Mapper\Module_Configuration\Controllers_Export_Data_Mapper

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Data_Mapper\Module_Configuration\Module_Configuration_Export_Data_Mapper_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Data_Mapper\Module_Configuration_Export_Data_Mapper
    arguments:
      $moduleStateService: '@Oxid_Esales\Eshop_Community\Internal\Framework\Module\State\Module_State_Service_Interface'
      $context: '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface'
      $dataMappers:
        - '@oxid_esales.module.configuration.class_extensions_export_data_mapper'
        - '@oxid_esales.module.configuration.controllers_export_data_mapper'


  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Module_Configuration_Data_Mapper_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Bridge\Module_Configuration_Data_Mapper_Bridge
    arguments:
      - '@Oxid_Esales\Eshop_Community\Internal\Framework\Module\Configuration\Data_Mapper\Module_Configuration\Module_Configuration_Export_Data_Mapper_Interface'
    public: true

