services:
  _defaults:
    autowire: true
    public: false

  Oxid_Esales\Eshop\Core\Language:
    factory: ['Oxid_Esales\Eshop\Core\Registry', 'getLang']

  Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Translator\Translator_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Transition\Adapter\Translator\Legacy_Template_Translator
    arguments:
      - '@Oxid_Esales\Eshop\Core\Language'
