services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Bridge\Module_Activation_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Bridge\Module_Activation_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Module_Dependency_Resolver_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Module_Dependency_Resolver

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Module_Activation_Service_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Module_Activation_Service
    arguments:
      $deactivationDependencyValidator: '@oxid_esales.module.setup.validator.deactivation_dependency_validator'

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Module_Services_Importer_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Module_Services_Importer

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Module_Configuration_Validator_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Module_Configuration_Validator_Aggregate
    arguments:
      - '@oxid_esales.module.setup.validator.activation_dependency_validator'
      - '@oxid_esales.module.setup.validator.controllers_module_setting_validator'
      - '@oxid_esales.module.setup.validator.class_extensions_module_setting_validator'
      - '@oxid_esales.module.setup.validator.events_module_setting_validator'
      - '@oxid_esales.module.setup.validator.services_yaml_validator'

  oxid_esales.module.setup.validator.controllers_module_setting_validator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Controllers_Validator

  oxid_esales.module.setup.validator.class_extensions_module_setting_validator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Class_Extensions_Validator

  oxid_esales.module.setup.validator.events_module_setting_validator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Events_Validator

  oxid_esales.module.setup.validator.activation_dependency_validator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Activation_Dependency_Validator

  oxid_esales.module.setup.validator.deactivation_dependency_validator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Deactivation_Dependency_Validator

  oxid_esales.module.setup.validator.services_yaml_validator:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Validator\Services_Yaml_Validator
    arguments:
      - '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface'

  oxid_esales.module.setup.service.eventsubscriber.dispatch_legacy_events_subscriber:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Event_Subscriber\Dispatch_Legacy_Events_Subscriber
    tags:
      - { name: kernel.event_subscriber }

  oxid_esales.module.setup.service.eventsubscriber.event_logging_subscriber:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Event_Subscriber\Event_Logging_Subscriber
    tags:
      - { name: kernel.event_subscriber }

  Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Active_Class_Extension_Chain_Resolver_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Module\Setup\Service\Active_Class_Extension_Chain_Resolver
    public: true
