services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Image_Handler_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Master_Image_Handler
    arguments:
      - "@oxid_esales.symfony.file_system"
      - '@Oxid_Esales\Eshop_Community\Internal\Transition\Utility\Context_Interface'

  Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Bridge\Master_Image_Handler_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Bridge\Master_Image_Handler_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\File_System\File_Generator\File_Generator_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\File_System\File_Generator\Csv_File_Generator

  Oxid_Esales\Eshop_Community\Internal\Framework\File_System\File_Generator\Bridge\File_Generator_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\File_System\File_Generator\Bridge\Csv_File_Generator_Bridge
    public: true

  Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Validator\File_Validator_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Validator\File_Validator
    arguments:
      - "@oxid_esales.symfony.mime_types"

  Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Validator\File_Validator_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\File_System\Validator\File_Validator_Bridge
    public: true
