services:
    _defaults:
        autowire: true

    Oxid_Esales\Eshop_Community\Internal\Domain\Admin\Command\Create_User_Command:
        class: Oxid_Esales\Eshop_Community\Internal\Domain\Admin\Command\Create_User_Command
        tags:
            - { name: 'console.command', command: 'oe:admin:create-user' }
