parameters:
    oxid_esales.email.disable_order_emails: false

services:
    _defaults:
        autowire: true
        public: false

    Oxid_Esales\Eshop_Community\Internal\Utility\Email\Email_Validator_Service_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Utility\Email\Email_Validator_Service

    Oxid_Esales\Eshop_Community\Internal\Utility\Email\Email_Validator_Service_Bridge_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Utility\Email\Email_Validator_Service_Bridge
        public: true
