services:
  _defaults:
    autowire: true
    public: false

  Oxid_Esales\Eshop_Community\Internal\Domain\Admin\Factory\Admin_Factory_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Admin\Factory\Admin_Factory