services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Migration\Migration_Executor_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Migration\Migration_Executor
