imports:
    - { resource: bootstrap-services.yaml }

services:
    _defaults:
        autowire: true

    Oxid_Esales\Eshop_Community\Internal\Container\Event\Configuration_Changed_Event_Subscriber:
        class: Oxid_Esales\Eshop_Community\Internal\Container\Event\Configuration_Changed_Event_Subscriber
        tags:
            - { name: kernel.event_subscriber }
