services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Logger\Factory\Logger_Factory_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Logger\Factory\Monolog_Logger_Factory
    arguments:
      $loggerName: 'OXID Logger'
      $logFilePath: '@=service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").getLogFilePath()'
      $logLevel: '@=service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").getLogLevel()'

  oxid_esales.monolog.logger:
    class: Monolog\Logger
    factory: ['@Oxid_Esales\Eshop_Community\Internal\Framework\Logger\Factory\Logger_Factory_Interface', 'create']

  Psr\Log\Logger_Interface:
    alias: 'oxid_esales.monolog.logger'
    public: true

