imports:
  - { resource: Database/services.yaml }
  - { resource: Directory/services.yaml }
  - { resource: Htaccess/services.yaml }
  - { resource: Language/services.yaml }
  - { resource: Validator/services.yaml }
  - { resource: Parameters/services.yaml }
  - { resource: ShopConfiguration/services.yaml }

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Setup\Shop_Setup_Command:
    class: Oxid_Esales\Eshop_Community\Internal\Setup\Shop_Setup_Command
    tags:
      - { name: 'console.command', command: 'oe:setup:shop' }