services:
  _defaults:
    autowire: true
    public: false

  Oxid_Esales\Eshop_Community\Internal\Utility\Url\Url_Parser_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Utility\Url\Url_Parser