services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Data_Mapper\Product_Rating_Data_Mapper_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Data_Mapper\Product_Rating_Data_Mapper
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Data_Mapper\Rating_Data_Mapper_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Data_Mapper\Rating_Data_Mapper
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Data_Mapper\Review_Data_Mapper_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Data_Mapper\Review_Data_Mapper
