imports:
  - { resource: parameters.yaml }

services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Framework\Mailing\Factory\Transport_Factory_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Framework\Mailing\Factory\Transport_Factory
    arguments:
      $dsn: '%oxid_esales.mailing.dsn%'

  Symfony\Component\Mailer\Transport\Transport_Interface:
    factory: ['@Oxid_Esales\Eshop_Community\Internal\Framework\Mailing\Factory\Transport_Factory_Interface', 'create']

  Symfony\Component\Mailer\Mailer_Interface:
    class: Symfony\Component\Mailer\Mailer
    arguments:
      $transport: '@Symfony\Component\Mailer\Transport\Transport_Interface'
      $bus: null
      $dispatcher: '@Symfony\Component\Event_Dispatcher\Event_Dispatcher_Interface'
    public: true
