services:
    _defaults:
        autowire: true

    Oxid_Esales\Eshop_Community\Internal\Setup\Database\Setup_Db_Connection_Factory_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Setup\Database\Setup_Db_Connection_Factory

    Oxid_Esales\Eshop_Community\Internal\Setup\Database\Views_Generator_Factory_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Setup\Database\Views_Generator_Factory

    Oxid_Esales\Eshop_Community\Internal\Setup\Database\Shop_Db_Manager_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Setup\Database\Shop_Db_Manager

    Oxid_Esales\Eshop_Community\Internal\Setup\Database\Setup_Db_Connection_Validator_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Setup\Database\Setup_Db_Connection_Validator

    Oxid_Esales\Eshop_Community\Internal\Setup\Database\Setup_Db_Validator_Interface:
        class: Oxid_Esales\Eshop_Community\Internal\Setup\Database\Setup_Db_Validator
