services:
  _defaults:
    autowire: true

  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\User_Review_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\User_Review_Bridge
    public: true
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\User_Rating_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\User_Rating_Bridge
    public: true
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\Product_Rating_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\Product_Rating_Bridge
    public: true
  Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\User_Review_And_Rating_Bridge_Interface:
    class: Oxid_Esales\Eshop_Community\Internal\Domain\Review\Bridge\User_Review_And_Rating_Bridge
    public: true
